### ISSUE TITLE
FileNotFoundError for jwst data Extraction 

### ISSUE THREAD

**Issue by karatmate** [spacetelescope/jdat_notebooks#115]
Can anyone help me how I can resolve this error? I have followed the instruction given in https://spacetelescope.github.io/jdat_notebooks/install.html
 but still seem to have some type of error: 
"FileNotFoundError: Unable to fetch schema from non-file URL: http://stsci.edu/schemas/jwst_datamodel/image.schema".

![MicrosoftTeams-image](https://user-images.githubusercontent.com/121525733/210101700-1a729265-e10b-48db-bac3-969464106761.png)

**Comment by camipacifici** [comment]
Hi @karatmate, this problem is caused by a mismatch of versions between stcal, jwst, and asdf. Can you please paste here the versions you are using for these three packages?
I am assuming this is the same problem you reported [here](https://github.com/spacetelescope/jdat_notebooks/issues/52#issuecomment-1367943085).

**Comment by karatmate** [comment]
Hello, @camipacifici  Thank you very much for helping me resolve this issue, I appreciate it alot. Yes, that is also the problem that I posted. The versions of stcal and asdf are as below: 
Name: stcal ; Version: 1.3.0
Name: asdf; Version: 2.14.3
I couldn't use pip install jwst to install the package maybe because I am in windows, but I can attach the problem it shows when I try to use that code. So instead I use GitHub to clone this jwst:  https://github.com/spacetelescope/jwst.git

This is the first error code I get:
![1st error code](https://user-images.githubusercontent.com/121525733/210568925-ba3f5101-f2c8-4d39-9976-07fd5e1df077.png)


This is whats written in the end of the error code:

![Last error codde](https://user-images.githubusercontent.com/121525733/210568930-4b69e85a-b4f6-4be5-bc9f-e21158ded635.png)

I did try and install visual studio C++ packages but it didn't do any difference.  If there's any way I can get it to work, it would be amazing! thank you!

**Comment by camipacifici** [comment]
Hi @karatmate, I did not realize you are on a windows machine. Unfortunately, windows is not currently supported for the jwst package (as mentioned on the readme of the [jwst github repository](https://github.com/spacetelescope/jwst)).
Any chance you can use a different machine or a linux virtual machine on your windows machine?

**Comment by karatmate** [comment]
> 

Thank you for your response. I used my mac to get the data sorted. I had an error initially which was solved by installing xcode. But regardless thanks for your help.

**Comment by camipacifici** [comment]
Glad you managed to solve the issue!
