### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/jdat_notebooks#12]
The readme would probably benefit from some further instructions on installation, in an explicit section on installation. Might be worth watching a new user try to get them all to run from scratch and seeing what the pain points are.

**Comment by haticekaratay** [comment]
Thank you for your feedback. We are pleased to inform you that the installation instructions are available on the following page: https://spacetelescope.github.io/jdat_notebooks/install.html.
