### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [spacetelescope/jdat_notebooks#125]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by pllim** [comment]
p.s. I also enabled the beta reporting feature that you mentioned. I did not know that is separate from the button you get in the issue template. Hope it works for you now. Thanks again!
