### ISSUE TITLE
Transfer new MRS Notebook from dat_pyinthesky

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdat_notebooks#47]
Transfer and render.

https://github.com/spacetelescope/dat_pyinthesky/blob/main/jdat_notebooks/MRS_Mstar_analysis/JWST_Mstar_dataAnalysis_PointSourceDetectorBasedExtraction.ipynb

**Comment by TheRealZoidberg** [comment]
Committed notebook to jdat_notebooks repo
