### ISSUE TITLE
Broken Notebook: Example of Converting a FITS File to ASDF

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdat_notebooks#48]
https://spacetelescope.github.io/jdat_notebooks/notebooks/asdf_example/asdf_example.html

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 cutout_file = fits_cut(input_files, center_coord, cutout_size, 
      2                        drop_after="", single_outfile=True)

TypeError: fits_cut() got an unexpected keyword argument 'drop_after'`

**Comment by haticekaratay** [comment]
Thanks for reporting the issue. The notebook was recently updated. You can view the latest version [here]( https://spacetelescope.github.io/jdat_notebooks/notebooks/asdf_example/asdf_example.html)
