### ISSUE TITLE
Broken Notebook: Imaging Sky Background Estimation

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdat_notebooks#49]
https://spacetelescope.github.io/jdat_notebooks/notebooks/background_estimation_imaging/Imaging%20Sky%20Background%20Estimation.html

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [2], in <cell line: 17>()
     15 from scipy.ndimage.filters import median_filter
     16 from astropy.modeling import models, fitting
---> 17 from astropy.nddata.utils import block_reduce

ImportError: cannot import name 'block_reduce' from 'astropy.nddata.utils' (/usr/share/miniconda/lib/python3.9/site-packages/astropy/nddata/utils.py)

`

**Comment by haticekaratay** [comment]
Hey @orifox, the notebook was recently updated. You can view the latest version here: https://spacetelescope.github.io/jdat_notebooks/notebooks/background_estimation_imaging/Imaging_Sky_Background_Estimation.html.
