### ISSUE TITLE
Broken Notebook: Draft Aperture Photometry

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdat_notebooks#53]
https://spacetelescope.github.io/jdat_notebooks/notebooks/aperture_photometry/NIRCam_Aperture_Photometry_Example.html

`FileNotFoundError: Unable to fetch schema from non-file URL: http://stsci.edu/schemas/jwst_datamodel/image.schema

`

**Comment by haticekaratay** [comment]
Hi @orifox, the notebook has been updated, and you can now view the fully rendered version without any issues. Here's the link: https://spacetelescope.github.io/jdat_notebooks/notebooks/aperture_photometry/NIRCam_Aperture_Photometry_Example.html

**Comment by haticekaratay** [comment]
Hi @orifox, the notebook has been updated, and you can now view the fully rendered version without any issues. Here's the link: https://spacetelescope.github.io/jdat_notebooks/notebooks/aperture_photometry/NIRCam_Aperture_Photometry_Example.html
