### ISSUE TITLE
Notebook Missing: IFU Cube Continuum

### ISSUE THREAD

**Issue by orifox** [spacetelescope/jdat_notebooks#55]
Missing notebook here: https://github.com/spacetelescope/jdat_notebooks/tree/main/notebooks/IFU_cube_continuum_fit

Notebook should be from here: https://github.com/spacetelescope/dat_pyinthesky/tree/main/jdat_notebooks/IFU_cube_continuum_fit

**Comment by TheRealZoidberg** [comment]
Notebook added
